.PHONY: fmt clippy test build ci check-wasm build-wasm hooks \
	download all smoke pipeline-clean

PY ?= python3

hooks:
	git config core.hooksPath .githooks
	@echo "pre-push hook activated (.githooks/pre-push)"

fmt:
	cargo fmt

clippy:
	cargo clippy -- -D warnings

test:
	cargo test

build:
	cargo build

build-native:
	RUSTFLAGS="-C target-cpu=native" cargo build --release

check-wasm:
	cargo check --target wasm32-unknown-unknown --no-default-features --features wasm

build-wasm:
	wasm-pack build --no-default-features --features wasm
	@printf '# Legacy artifacts from old crate name\ngamlss_rs*\n# Regenerated by wasm-pack; license is tracked at the repo root\nLICENSE\n' > pkg/.gitignore

ci: fmt clippy test build-native

# ---- Fire-perimeter data pipeline (pipeline/, see NOTES.md) ----

# Fetch raw inputs and write data/raw/MANIFEST.json checksums.
download:
	$(PY) -m pipeline.download

# Run stages s01-s09 -> artifacts/fires_enriched.parquet (needs `make download` first).
all:
	$(PY) -m pipeline.run_all

# Full pipeline on synthetic fixtures + determinism check; no network needed.
smoke:
	$(PY) scripts/smoke_pipeline.py

pipeline-clean:
	rm -rf data/interim data/processed artifacts/fires_enriched.parquet
